modify error message spesificity

diff --git a/.github/workflows/run-security-scans.yml b/.github/workflows/run-security-scans.yml
--- a/.github/workflows/run-security-scans.yml
+++ b/.github/workflows/run-security-scans.yml
@@ -37,6 +37,8 @@ env:
   SERVICE_ACCOUNT: ${{ inputs.service_account }}
   IMAGE_URL: ${{ inputs.image_url }}
   ATTESTOR_PROJECT_ID: kubernetes-dev-94b9
+  BRANCH: ${{ github.ref_name }}
+  EVENT_NAME: ${{ github.event_name }}
 
 jobs:
   setup-env:
@@ -193,10 +195,14 @@ jobs:
       - name: Check for Critical and High Severity
         id: severity_check
         run: |
-          severity_check=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts?ref=${{github.ref}} | jq '[.[] | select(.state == "open" and (.rule.security_severity_level == "high" or .rule.security_severity_level == "critical"))] | any')
-          if [[ $severity_check == 'true' ]]
+          severity_check=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts?ref=${{github.ref}} | jq '[.[] | select(.state == "open" and (.rule.security_severity_level == "high" or .rule.security_severity_level == "critical"))] | any') 
+          if [[ $severity_check == 'true' &&  $EVENT_NAME == 'pull_request' ]]
           then
             echo "Error: High or critical vulnerabilities detected. Go to the Code Scanning section of the Github Security-tab to review these vulnerabilities. If this is a pull request, search for 'is:open pr:<pr-number>'";
+            exit 1;
+          elif [[ $severity_check == 'true' && ($BRANCH == 'main' || $BRANCH == 'master')]]
+          then
+            echo "Error: High or critical vulnerabilities detected. Go to the Code Scanning section of the Github Security-tab to review these vulnerabilities.";
             exit 1;
           else
             echo "Success! No high or critical code scanning alerts."
