Use tailscale if cyrilgdn/postgresql provider is present

diff --git a/.github/workflows/run-terraform.yml b/.github/workflows/run-terraform.yml
--- a/.github/workflows/run-terraform.yml
+++ b/.github/workflows/run-terraform.yml
@@ -121,6 +121,7 @@ env:
   ARM_CLIENT_ID: ${{ secrets.arm_client_id }}
   ARM_CLIENT_SECRET: ${{ secrets.arm_client_secret }}
   ARM_TENANT_ID: ${{ secrets.arm_tenant_id }}
+  NEED_TAILSCALE: false
 
 jobs:
   setup-env:
@@ -245,6 +246,26 @@ jobs:
           terraform fmt -check -recursive -no-color || { echo '
           FAILURE! The above files are not properly formatted.
           Run `terraform fmt` in $WORKING_DIRECTORY, commit the changed files and push to fix the issue' | tee -a $GITHUB_STEP_SUMMARY ; exit 1; }
+
+      - name: Check for PostgreSQL Provider
+        id: check_postgresql
+        run: |
+          PROVIDER_CHECK=$(terraform providers | grep cyrilgdn/postgresql) || true
+          if [ -n "$PROVIDER_CHECK" ]; then
+            echo "PostgreSQL provider found."
+            echo "NEED_TAILSCALE=true" >> $GITHUB_ENV
+          else
+            echo "PostgreSQL provider not found."
+            echo "NEED_TAILSCALE=false" >> $GITHUB_ENV
+          fi
+
+      - name: Tailscale
+        if: env.NEED_TAILSCALE == 'true'
+        uses: tailscale/github-action@v2
+        with:
+          oauth-client-id: ${{ secrets.TS_CLOUDSQL_OAUTH_CLIENT_ID }}
+          oauth-secret: ${{ secrets.TS_CLOUDSQL_OAUTH_SECRET }}
+          tags: tag:cloudsql-user
 
       - name: Terraform Plan
         id: plan
