test

diff --git a/.github/workflows/run-security-scans.yml b/.github/workflows/run-security-scans.yml
--- a/.github/workflows/run-security-scans.yml
+++ b/.github/workflows/run-security-scans.yml
@@ -197,9 +197,8 @@ jobs:
           severity_check=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts | jq -e '[.[] | select(.state == "open" and (.rule.security_severity_level == "high" or .rule.security_severity_level == "critical"))] | any')
           if [[ $severity_check == 'true' ]]
           then
-            echo "Error";
+            {echo "Error: High or critical vulnerabilities detected. Go to the Code Scanning section of the Github Security-tab to review these vulnerabilities. If this is a pull request, search for pr:<number>" && exit 1;}
           fi
-          exit 1
 
   attest:
     name: Attest Github Security Code Scanning
