Fix issues with github-workflows (#36)

diff --git a/.github/workflows/run-security-scans.yml b/.github/workflows/run-security-scans.yml
--- a/.github/workflows/run-security-scans.yml
+++ b/.github/workflows/run-security-scans.yml
@@ -6,7 +6,7 @@ on:
       # The image reference generated by a build job.
       image_url:
         description: "An image_url of the form registry/repository:tag."
-        required: true
+        required: false
         type: string
       auth_project_number:
         description: "The GCP Project Number used for authentication. A 12-digit number used as a unique identifier for the project. Used to find workload identity pool."
@@ -37,12 +37,16 @@ env:
   SERVICE_ACCOUNT: ${{ inputs.service_account }}
   IMAGE_URL: ${{ inputs.image_url }}
   ATTESTOR_PROJECT_ID: kubernetes-dev-94b9
+  REGISTRY: ghcr.io
+  BRANCH: ${{ github.ref_name }}
+  HEAD_REF: ${{ github.head_ref }}
+  EVENT_NAME: ${{ github.event_name }}
 
 jobs:
   setup-env:
     runs-on: ubuntu-latest
     outputs:
-      workload_identity_provider: ${{ steps.set-output.outputs.WORKLOAD_IDENTITY_PROVIDER }}
+      WORKLOAD_IDENTITY_PROVIDER: ${{ steps.set-output.outputs.WORKLOAD_IDENTITY_PROVIDER }}
     steps:
       - name: Set vars
         id: set-output
@@ -79,13 +83,20 @@ jobs:
 
   trivy:
     name: Trivy
-    if: inputs.trivy == true && github.event.pull_request.draft == false
+    if: inputs.trivy == true && inputs.image_url != '' && github.event.pull_request.draft == false
     needs: [setup-env]
     runs-on: ubuntu-latest
     # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
     defaults:
       run:
         shell: bash
+    permissions:
+      contents: read
+      packages: write
+      # required for authentication to GCP
+      id-token: write
+      actions: read
+      security-events: write
     env:
       WORKLOAD_IDENTITY_PROVIDER: ${{ needs.setup-env.outputs.WORKLOAD_IDENTITY_PROVIDER }}
     steps:
@@ -93,8 +104,18 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Log into registry
+        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Docker pull image
+        run: docker pull $IMAGE_URL
+
       - name: Run Trivy vulnerability scanner
-        uses: aquasecurity/trivy-action@master
+        uses: aquasecurity/trivy-action@9ab158e8597f3b310480b9a69402b419bc03dbd5
         with:
           image-ref: ${{ env.IMAGE_URL }}
           format: sarif
@@ -172,15 +193,24 @@ jobs:
       - name: Check for Critical and High Severity
         id: severity_check
         run: |
-          severity_check=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts | jq -e '[.[] | select(.state == "open" and (.rule.security_severity_level == "high" or .rule.security_severity_level == "critical"))] | any')
-          if [[ $severity_check == 'true' ]]
+          severity_check=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts?ref=${{github.ref}} | jq '[.[] | select(.state == "open" and (.rule.security_severity_level == "high" or .rule.security_severity_level == "critical"))] | any') 
+          if [[ $severity_check == 'true' &&  $EVENT_NAME == 'pull_request' ]]
           then
-            echo "Error: High or critical vulnerabilities detected. Go to the Code Scanning section of the Github Security-tab to review these vulnerabilities."
-            exit 1
+            pr_number=$( echo $BRANCH | sed 's/\/.*//')
+            echo "Error: High or critical vulnerabilities detected on pull-request. Go to the Code Scanning section of the Github Security-tab and search for 'is:open pr:$pr_number' to review these vulnerabilities.";
+            exit 1;
+          elif [[ $severity_check == 'true' && ($BRANCH == 'main' || $BRANCH == 'master')]]
+          then
+            echo "Error: High or critical vulnerabilities detected on main/master branch. Go to the Code Scanning section of the Github Security-tab to review these vulnerabilities.";
+            exit 1;
+          else
+            echo "Success! No high or critical code scanning alerts."
           fi
+          
 
   attest:
     name: Attest Github Security Code Scanning
+    if: inputs.image_url != ''
     needs: [tfsec, trivy, check-github-security, setup-env]
     runs-on: ubuntu-latest
     # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
@@ -199,6 +229,13 @@ jobs:
         with:
           workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
           service_account: ${{ env.SERVICE_ACCOUNT }}
+
+      - name: Log into registry
+        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Get Image Digest URL from Image Tag URL
         id: image-digest-url
